### PR TITLE
Update org.nomacs.ImageLounge.json to new beta release 3.17.2297 Beta

### PR DESCRIPTION
**Pull request by lightwisephoto**
Updated beta branch to newest beta release of nomacs. See: https://github.com/nomacs/nomacs/releases

While nomacs hasn't seen a major release for years, some bug fixes (especially _Remove implicit auto-save_ in [3.17.2282 Beta](https://github.com/nomacs/nomacs/releases/tag/3.17.2282)) have been committed to beta versions.

To reflect this and give non-developer users a chance to benefit from the betas, the flatpak's beta branch is now on a par with the github beta releases of nomacs.

NB: First flathub related commit for me, so feel free to edit, correct, comment ...

### CODE REVIEW

**Comment by lightwisephoto** [comment]
Okay, build succeeds, but build validation fails with appstream errors (due to the screenshots?) although I merged the master branch (including the screenshot patch) beforehand.

```
{
    "errors": [
        "appstream-failed-validation"
    ],
    "warnings": [
        "appstream-summary-too-long",
        "appstream-name-too-long",
        "appstream-screenshot-missing-caption"
    ],
    "appstream": [
        "E: org.nomacs.ImageLounge:36: screenshot-no-media",
        "E: org.nomacs.ImageLounge:37: screenshot-no-media"
    ],
    "message": "Please consult the documentation at https://docs.flathub.org/docs/for-app-authors/linter"
}
```

**Comment by hfiguiere** [comment]
because it didn't fix that, just the URL. 

URL must be inside `<image>`. See https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-screenshots

This wasn't enforced, but in the last few month we changed tooling and it's more strict.

**Comment by lightwisephoto** [comment]
> URL must be inside `<image>`. See https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-screenshots

Great. That did the trick (and I learned something new). Thank you so much.

**Comment by lightwisephoto** [comment]
Hi out there.

Would one mind to merge this PR? Is something missing?

When merged every flathub user could profit from being able to use the latest beta.

**Comment by hfiguiere** [comment]
bot, build

**Pull request merged**
